### ISSUE TITLE
[Feature Request] Non pi@10.0.0.2 address

### ISSUE THREAD

**Issue by JD-2006** [cyberartemio/wof-pwnagotchi-plugin#16]
Would be great to use the bt-teher address since I don't use a usb connection.

**Comment by cyberartemio** [comment]
What do you mean? 😊

**Comment by cyberartemio** [comment]
I re-read your message and I think that I understood what you meant. You can use the BT IP of the pwnagotchi instead of the USB IP, it doesn't matter. You should use the IP address of your pwnagotchi to reach the web ui.

As a side note: I added `10.0.0.2` to the README just as an example. I'm gonna change the docs so it'd be more clear.
